name: Application CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev # dev environment
      - main # prod environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          APP_NAME=${{ vars.APP_NAME }}
          TAG=${{ github.sha }}

          docker build -t $APP_NAME -t $APP_NAME:$TAG .
          echo "Success: Built $APP_NAME with tag: $TAG"
